#!/bin/zsh
usage='usage: visrc <filename>
    alias for vi $(which <filename>) if exist
options:
    --help - show this usage message'

if test $# -ne 1 || test $1 = '--help'; then
    echo $usage
    return 0
fi

fp=$(which $1)
if test $? -ne 0; then
    echo $fp
    return 1
fi
if test ! -f $fp; then
    echo "$fp: regular file not exist"
    return 2
fi

vi $fp
